### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: Invalid Parameter - /content

### ISSUE THREAD

**Issue by ClayAssis** [filipedeschamps/video-maker#145]
Ola

Eu to encontrando o seguinte erro qdo executo

"Type a Wikipedia search term: bird

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
 [0][0] Baixou imagem com sucesso: https://sites.google.com/site/vidya2018mydre
am26/_/rsrc/1538709509145/home/1920_year-of-the-bird-george-grall.jpg
 [1][0] Baixou imagem com sucesso: https://lh3.googleusercontent.com/AsJM8McxfW
ZhEohcHVIahDIttHb_UKN5qKV3k6W0AT6KoJEAw78MNFYHv0zuQ0Iv_Ys=w720-h310
 [2][0] Erro ao baixar (https://sites.google.com/site/vidya2018mydream26/_/rsrc
/1538709509145/home/1920_year-of-the-bird-george-grall.jpg): Error: Imagem já fo
i baixada
 [2][1] Baixou imagem com sucesso: https://sites.google.com/site/endangeredbird
sp/_/rsrc/1548836186272/home/500_F_224977359_CVWEHO27dISOaY6uUzCCyMp8KamNMyDO%20
%281%29.jpg
 [3][0] Baixou imagem com sucesso: https://i2.wp.com/ae01.alicdn.com/kf/HTB1tZf
AEh1YBuNjy1zcq6zNcXXau/1PCS-Parrot-Products-font-b-Bird-b-font-Mirror-font-b-Bir
d-b-font-Cage-Station.jpg_300x300q75.jpg?crop=5,2,900,500&quality=2886
 [4][0] Baixou imagem com sucesso: https://sites.google.com/site/detamostranah/
_/rsrc/1385355105312/naturalworld/flightless-birds/204501_463458.jpg
 [5][0] Baixou imagem com sucesso: http://upload.wikimedia.org/wikipedia/common
s/5/58/Bird_respiration_air_flow_schematic.png
[6][0] Erro ao baixar (https://sites.google.com/site/endangeredbirdsp/_/rsrc/1
548836186272/home/500_F_224977359_CVWEHO27dISOaY6uUzCCyMp8KamNMyDO%20%281%29.jpg
): Error: Imagem já foi baixada
 [6][1] Baixou imagem com sucesso: https://sites.google.com/site/endangeredbird
sp/_/rsrc/1548834917583/home/nature-wallpaper12.jpg
(node:6652) UnhandledPromiseRejectionWarning: Error: Command failed: Invalid Par
ameter - /content
    at ChildProcess.onExit (C:\Users\Clay\video-maker\node_modules\gm\lib\comman
d.js:301:17)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (C:\Users\Clay\video-maker\node_modules\cross-spawn\
lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:6652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:6652) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code."

Alguma idea do que pode ser?

**Comment by ClayAssis** [comment]
Percebi que isso sempre acontece depois de baixar 6 fotos. Caso ajude!

**Comment by rafaelkamp** [comment]
https://github.com/filipedeschamps/video-maker/issues/110#issuecomment-480595553

**Comment by ClayAssis** [comment]
Vlw
Eu procurei erro parecido, mas havia achado. Desculpa a redundância!

**Comment by dionesrosa** [comment]
Este erro deu para mim também. Mas foi por que eu tinha instalado o arquivo errado do imagemagick.
Resolvi instalando o arquivo com final -dll.exe retirado do site: https://imagemagick.org/script/download.php (na parte de: Windows Binary Release). Basta escolher o arquivo de acordo com sua arquitetura, se é 32 ou .64 bits.
