### ISSUE TITLE
Erro após autenticar com o Auth2

### ISSUE THREAD

**Issue by jpfurlan** [filipedeschamps/video-maker#153]
Consegui consentir o acesso a conta no entanto após apareceu o seguinte erro.

> expiry_date: 1556719472310 }

> (node:2736) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or > dir
> ectory, stat './content/output.mov'
>     at Object.statSync (fs.js:850:3)
>     at uploadVideo (C:\Users\PC\Desktop\video-maker\video-maker\robots\youtube.j> 
> s:108:30)
 >    at Object.robot [as youtube] (C:\Users\PC\Desktop\video-maker\video-> maker\ro
bots\youtube.js:12:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:2736) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by doug-simon** [comment]
Eu estou com exatamente o mesmo erro. Vamos trocar algumas figurinhas para ver o que cada um fez e tentar eliminar possibilidades.
O que eu tentei até agora e não funcionou:
**1) Trocar o caminho em:**
      const destinationFilePath = `${rootPath}/Desktop/Video Maker/Projeto/video-maker/content/output.mov`
para:
             const destinationFilePath = 'C:\\Users\\Desktop\\Video Maker\\Projeto\\video-maker\\content\\output.mov'

**2) Tocar o caminho do eval aqui:**
![image](https://user-images.githubusercontent.com/49952136/57091435-92eca580-6cdf-11e9-9c14-a9d40f61ab0e.png)

**3) Trocar o endereço de saída aqui (P.s. Eu não entendo de AE):**
![image](https://user-images.githubusercontent.com/49952136/57091524-d3e4ba00-6cdf-11e9-9f25-552bc7f1c8c8.png)

Como estão tuas tentativas?

**Comment by jpfurlan** [comment]
como que eu abro o After effects pra alterar o endereço de saída?

**Comment by hebertlima** [comment]
o arquivo **output.mov** está aparecendo dentro da pasta **content/**?

**Comment by doug-simon** [comment]
> como que eu abro o After effects pra alterar o endereço de saída?

@jpfurlan Não entendi a pergunta. Tu tem o AE em qual versão?

**Comment by doug-simon** [comment]
> o arquivo **output.mov** está aparecendo dentro da pasta **content/**?

Olá @hebertlima,

Se eu mando publicar no AE ele cria o arquivo na pasta content/, porém pelo robot parece fazer quase tudo, mas não reconhece no final.

Eu alterei minhas configurações no video.js para:

      const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects CC 2019\\Support Files\\aerender.exe'
      const templateFilePath = `${rootPath}/Desktop/Video Maker/Projeto/video-maker/templates/1/template.aep`
      const destinationFilePath = `${rootPath}/Desktop/Video Maker/Projeto/video-maker/content/output.mov`

Se eu já tiver um arquivo output.mov ele não aparecerá mais o erro dessa Issue, mas tenho um outro agora:

> 100% completed
> Video available at: https://youtu.be/9vhUaKTa5aQ
(node:4832) UnhandledPromiseRejectionWarning: Error: The authenticated user doesnt have permissions to upload and set custom video thumbnails.
    at Gaxios.<anonymous> (C:\Users\Douglas\Desktop\Video Maker\Projeto\video-maker\node_modules\gaxios\build\src\gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Douglas\Desktop\Video Maker\Projeto\video-maker\node_modules\gaxios\build\src\gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Neste, o youtube.js faz o upload, mas é do arquivo velho da pasta content/, pois o AE não salva o novo.

Eu continuo achando que meu problema é no AE e não nos robôs.

**Comment by hebertlima** [comment]
esse ultimo “erro” é de permissão de thumbnail, se o seu canal é “novo” o youtube precisa verificar sua conta antes de liberar a opção de thumbnail customizada, não é necessariamente um erro, depois que o youtube verificar sua conta ele libera, tenta apagar todo o conteúdo da pasta **content** deixando apenas o after effects.js pra ver se o **output.mov** esta sendo criado

**Comment by hebertlima** [comment]
@jpfurlan se você tiver o After Effects instalado, clica duas vezes no **template.aep** que ele abre

**Comment by MatheusRV** [comment]
@jpfurlan Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Esse erro parece persistir. Vamos mantê-lo para investigar.
