### ISSUE TITLE
Erro do Watson.

### ISSUE THREAD

**Issue by Beaast-exe** [filipedeschamps/video-maker#155]
(node:15688) UnhandledPromiseRejectionWarning: Unauthorized: Access is denied due to invalid credentials.
    at formatError (C:\Users\RafaelF\Desktop\DEV\2. JavaScript\youtube-video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:111:17)
    at C:\Users\RafaelF\Desktop\DEV\2. JavaScript\youtube-video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:259:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:15688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\RafaelF\Desktop\DEV\2. JavaScript\youtube-video-maker>

---

Não consigo saber o que causa este erro

**Comment by jpfurlan** [comment]
Você fez o passo corretamente do api watson dessa lista ?
https://github.com/filipedeschamps/video-maker/issues/89

**Comment by hebertlima** [comment]
você esta usando as credenciais inválidas da api, e esta recebendo um "acesso negado" nessa issue #89 tem um passo a passo para configurar a api do watson

**Comment by Beaast-exe** [comment]
eu fiz tudo dessa issua #89 ...

**Comment by hebertlima** [comment]
atualiza seu repositório no github, vou dar uma olhada

**Comment by Beaast-exe** [comment]
@hebertlima feito

**Comment by Beaast-exe** [comment]
@hebertlima já atualizei, pode ver la e me ajudar ?

**Comment by hebertlima** [comment]
abri uma pr no seu repo, a url da api do watson esta errada

**Comment by ArthurBottcher** [comment]
Alguem pode me ajudar ? 
estou tendo o seguinte erro:

C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\base_service.js:243
                throw new Error(errorMessage);
                ^

Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.
    at NaturalLanguageUnderstandingV1.BaseService.initCredentials (C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\base_service.js:243:23)
    at NaturalLanguageUnderstandingV1.BaseService (C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\base_service.js:98:29)
    at NaturalLanguageUnderstandingV1 [as constructor] (C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\natural-language-understanding\v1-generated.js:57:28)
    at new NaturalLanguageUnderstandingV1 (C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\natural-language-understanding\v1.js:19:23)
    at Object.<anonymous> (C:\Users\Biomecanica\VideoMakerRobots\robots\text.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)

**Comment by nomar113** [comment]
@Beaast-exe, eu acessei https://cloud.ibm.com/resources, exclui o serviço que tinha criado a primeira vez e recriei (segui os passos do vídeo novamente). Voltou a funcionar depois disso.

**Comment by MatheusRV** [comment]
@Beaast-exe Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by Lorhan7** [comment]
olha no site oficial do modulo do [Watson](https://www.npmjs.com/package/ibm-watson)
o Modelo para conexão é assim: 
```js
const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');
 
const nlu = new NaturalLanguageUnderstandingV1({
  authenticator: new IamAuthenticator({ apikey: '<apikey>' }),
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

```

ai no seu caso, tenta assim e ve se funciona:

```js
const watsonApiKey = require('../credentials/watson-nlu.json').apikey;


const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const nlu = new NaturalLanguageUnderstandingV1({
  authenticator: new IamAuthenticator({ apikey: watsonApiKey }),
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

```

**Comment by marcosCorreia** [comment]
Estou com o mesmo problema de autenticação do **watson** ele só autentica injetando o apikey de forma manual no código, teria alguem para me ajudar

**Comment by gmiranda13** [comment]
Eu tambem estava  com erros para acessar o watson, e como o @Lorhan7 mostrou, algumas coisas mudaram, porem eu continuei com o erro e fiz o seguinte:

Meu erro era: 
`(node:20844) UnhandledPromiseRejectionWarning: Forbidden: Access is denied due to invalid credentials`.

Para resolver verifique:
- Versão do nodejs >10
- Instale o  watson `npm install ibm-watson` (Instale as outras dependencias se necessario)
- Atualize a data da versão no codigo `version: XXXX-XX-XX` (pegue a mais atual no link abaixo)
- Atualize a sua url conforme é mostrado em Credentials (essa url tambem esta no .json, mas só consegui fazer funcionar assim).

E para finalizar esse link me ajudou bastante:
https://cloud.ibm.com/apidocs/natural-language-understanding/natural-language-understanding?code=node
*obs: não apenas copie e coloque todo o codigo do link, pois algumas variaveis estao diferente.

**Comment by tvaccari34** [comment]
Se voce atualizou a versao do ibm-watson como o @gmiranda13 informou e esta utilizando o arquivo watson-nlu.json como no video com as suas credenciais, pode usar o trecho de codigo abaixo que vai rolar:

```
const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const watsonUrl = require('../credentials/watson-nlu.json').url

const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const nlu = new NaturalLanguageUnderstandingV1({
  version: '2018-04-05',
  authenticator: new IamAuthenticator({
    apikey: watsonApiKey,
  }),
  url: watsonUrl,
});
```

**Comment by apfjunior** [comment]
:1st_place_medal: @tvaccari34 e @gmiranda13 :100:  Muito obrigado!!! Deu certo dessa forma: 

Instalar  pacote  completo ibm-watson:
```
npm install ibm-watson
```
E depois substituir as linhas que estava no vídeo pelas citadas pelo @tvaccari34 
```js
const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const watsonUrl = require('../credentials/watson-nlu.json').url

const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const nlu = new NaturalLanguageUnderstandingV1({
  version: '2018-04-05',
  authenticator: new IamAuthenticator({
    apikey: watsonApiKey,
  }),
  url: watsonUrl,
});
```

**Comment by tvaccari34** [comment]
Show @apfjunior!
