### ISSUE TITLE
Error: Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by Helesi** [filipedeschamps/video-maker#159]
Olá, fiz tudo conforme o que apareceu mas no fim de pesquisar dá este erro:

(node:2096) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:196:13)
    at Gunzip.<anonymous> (C:\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:284:20)
    at Gunzip.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
(node:2096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
Ola @Helesi, seu problema é de credenciais, da uma olhada no **readme** do projeto, lá foi documento o passo a passo pra vc criar todas as credenciais, do erro que você postou acredito que seja nas credenciais do **watson da IBM**

**Comment by arturcorvino** [comment]
@Helesi você conseguiu resolver? Estou tendo o mesmo problema.

**Comment by MatheusRV** [comment]
@Helesi Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando por inatividade. Por favor, reabra caso tenha erro e mais informações.
