### ISSUE TITLE
Google Cloud

### ISSUE THREAD

**Issue by OTommyOne** [filipedeschamps/video-maker#163]
É possível fazer sem o Google Cloud ???

**Comment by hebertlima** [comment]
resposta curta: não.
vou te explicar o motivos:

algumas apis são de propriedade da google, e a única forma de interagir com elas, é  através do google cloud, porque?

o google cloud é uma plataforma que a google desenvolveu a princípio para gerir o serviços que rodavam na nuvem que era somente o “google cloud”, porém eles tiveram a ideia de centralizar todos os seus serviços de desenvolvimento em um lugar só, então por esse motivo você não consegue usar alguns serviços sem estar usando o google cloud, da mesma forma que você não consegue usar as apis sem ter uma conta gmail.

**Comment by jeronimojbarbosa** [comment]
sim é possível, baixe as imagens pra dentro da pasta contente e comente a chamada do image.js no index.js. Não esqueça de colocar as imagens com os nomes que iriam ser salvos originalmente, tipo ="0-original.png", "1-original.png" e assim por diante, ok?

**Comment by leodutra** [comment]
Enhancements:
- [ ] Documentar melhor a possibilidade de iniciar steps independentemente.
- [ ] Criar guards e parâmetros para facilitar esta opção.

**Comment by carlinhoshk** [comment]
Alguem ta conseguindo criar conta e usar a API do google ?

**Comment by Fredbeta** [comment]
O meu ta dando esse bug e não sei como resolver, acho que é no Google cloud tb

Microsoft Windows [versão 6.3.9600]
(c) 2013 Microsoft Corporation. Todos os direitos reservados.

C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>node index.j
s
internal/modules/cjs/loader.js:1222
    throw err;
    ^

SyntaxError: C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker
\credentials\google-search.json: Unexpected string in JSON at position 62
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1219
:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:923:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1074:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\alfre_000\Desktop\Alfredo\copia do reposotór
io\video-maker\robots\image.js:6:33)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1185:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m

C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>
