### ISSUE TITLE
Erro google-search.json

### ISSUE THREAD

**Issue by Cyberx9901** [filipedeschamps/video-maker#182]
segui todo o tutorial, porém quando tento rodar o programa aparece isso

cyber@cyber-pc:~/video-maker$ node index.js 
internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: /home/cyber/video-maker/credentials/google-search.json: Unexpected string in JSON at position 58
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/cyber/video-maker/robots/image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
cyber@cyber-pc:~/video-maker$

**Comment by hebertlima** [comment]
Olá @Cyberx9901 tem algum erro de sintax no arquivo **google-search.json**, veja se a pontuação esta correta, virgulas e aspas, deve-se parecer com isso:

```js
{
  "apiKey": "sua_api_key_aqui",
  "searchEngineId": "sua_search_id_aqui"
}
```

**Comment by Cyberx9901** [comment]
tinha faltado a virgula, obrigado por avisar
