### ISSUE TITLE
Error: Cannot find module '../credentials/algorithmia.json'

### ISSUE THREAD

**Issue by 8uch3ch4** [filipedeschamps/video-maker#186]
Bom dia Galera, 

Não estou conseguir prosseguir com o avanço desse Erro, sou um novato nesse ramo de programação, pelo que estou conseguindo percebe desse erro, e pelo que vi nos post de erros
o robo não esta conseguindo achar essa pasta ou está no caminho errado isso? 

gostaria de uma ajuda dos que sabem sobre isso

Muito obrigado por perde um tempo da sua vida a me ajuda.

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Usuario\video-maker\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PS C:\Users\Usuario\video-maker>

**Comment by 8uch3ch4** [comment]
tem essa explicação mas não entendi muito bem 

Oi, consegui replicar seu erro aqui.
Verifica os itens abaixo:

Nome da pasta "credentials"
Nome do arquivo "algorithmia.json"
No arquivo robot/text.js, const algorithmiaApiKey = require('../credentials/algorithmia.json') essa informação precisa ser extamente o nome do arquivo na pasta.
Obs.: Acredito que tenha algum erro de sintaxe em algum desses pontos, dessa forma o programa não acha o arquivo, ocasionando o erro.

qualquer coisa, sigo à disposição. =D

Creditos da fernanda

**Comment by eborguezao** [comment]
Código não funciona.
