### ISSUE TITLE
Failed when trying to start project:node index.js

### ISSUE THREAD

**Issue by gurisitchinava** [filipedeschamps/video-maker#187]
`internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: /Users/gurisitchinava/video-maker/credentials/google-search.json: Unexpected string in JSON at position 58
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/gurisitchinava/video-maker/robots/image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)`

This is error code when I trying to start project

**Comment by gurisitchinava** [comment]
![image](https://user-images.githubusercontent.com/16261118/58050893-a6ae5d80-7b61-11e9-8040-4657a748f11c.png)

**Comment by gurisitchinava** [comment]
I made everything correctly 
![image](https://user-images.githubusercontent.com/16261118/58050938-d65d6580-7b61-11e9-82c2-0aeea4963b3e.png) 

I used already **npm install** removed Package locker file rm -rf package-lock.json

**Comment by ChrysthianChrisley** [comment]
Está faltando uma vírgula após a "apiKey": "xxxxx"
