### ISSUE TITLE
Error ao colocar o comando node index.js

### ISSUE THREAD

**Issue by lanemello** [filipedeschamps/video-maker#196]
internal/modules/cjs/loader.js:798
    throw err;
    ^

SyntaxError: C:\Users\robo\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\robo\video-maker\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by cesarhilario** [comment]
é um erro no seu google-search.json, poste o código onde as vc acessa este json.

**Comment by lanemello** [comment]
{
  "apiKey": "api"
  "searchEngineId": "api"
}

**Comment by ChrysthianChrisley** [comment]
Estou com o mesmo erro.:

$ node index.js
internal/modules/cjs/loader.js:798
    throw err;
    ^

SyntaxError: D:\video-maker\video-maker\credentials\google-search.json: Unexpect
ed string in JSON at position 60
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\video-maker\video-maker\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by ChrysthianChrisley** [comment]
> internal/modules/cjs/loader.js:798
> throw err;
> ^
> 
> SyntaxError: C:\Users\robo\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
> at JSON.parse ()
> at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Module.require (internal/modules/cjs/loader.js:690:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> at Object. (C:\Users\robo\video-maker\robots\image.js:6:33)
> at Module._compile (internal/modules/cjs/loader.js:776:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

Está faltando uma vírgula após "apiKey": "api"

**Comment by DanielFelizardoDev** [comment]
O formato de JSON, é um objeto, e nele pode ter uma chave, que é o que quer procurar, com o seu valor, se tiver mais chaves, você precisa adicionar a vírgula ao final de cada.

**Comment by wfrsilva** [comment]
{
"apiKey": "api"**,**
"searchEngineId": "api"
}

Parece faltar virgula aqui, ja tive esse problema

**Comment by MatheusRV** [comment]
@lanemello Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando por inatividade. Por favor, reabra caso o erro persista e haja mais informações.
