### ISSUE TITLE
Código da erro ao utilizar função de preencher keywords

### ISSUE THREAD

**Issue by ArthurBottcher** [filipedeschamps/video-maker#202]

**Comment by ArthurBottcher** [comment]
preciso de ajuda.
quando tento usar a funçao pra pegar as keywords sempre da o mesmo erro:
(node:8964) UnhandledPromiseRejectionWarning: Unauthorized: Access is denied due to invalid credentials.
    at formatError (C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:111:17)
    at C:\Users\Biomecanica\VideoMakerRobots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:259:19
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:8964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
