### ISSUE TITLE
PROBLEMA NO NODE: 212

### ISSUE THREAD

**Issue by JuniorPetrini** [filipedeschamps/video-maker#209]
(node:212) UnhandledPromiseRejectionWarning: Error: {"context":{"requestId":"b38edae547f844538bc84e97f38433e8","requestType":"incoming.Identity_Token","userAgent":"NotSet","clientIp":"177.20.182.4","url":"https://iam.bluemix.net","instanceId":"iamid-4.2-6063-72deb72-5bdbfbc8f9-z77gg","threadId":"198903","host":"iamid-4.2-6063-72deb72-5bdbfbc8f9-z77gg","startTime":"16.07.2019 19:23:39:490 UTC","endTime":"16.07.2019 19:23:39:553 UTC","elapsedTime":"63","locale":"en_US","clusterName":"iam-id-prdal10-ljdb"},"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found"}
    at Request._callback (C:\Users\Junior\Meu-Projeto\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:113:21)
    at Request.self.callback (C:\Users\Junior\Meu-Projeto\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\Junior\Meu-Projeto\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\Junior\Meu-Projeto\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Oq fazer?

**Comment by DanielFelizardoDev** [comment]
Você está colocando uma API inválida, se tiver certo, provavelmente é algum parâmetro escrito de forma errada e tal, se tu poder postar teu código aqui!

**Comment by MatheusRV** [comment]
@JuniorPetrini Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando. Por favor reabra se persistir.
