### ISSUE TITLE
PROBLEMA NO NODE: 13256

### ISSUE THREAD

**Issue by JuniorPetrini** [filipedeschamps/video-maker#210]
(node:13256) UnhandledPromiseRejectionWarning: Error: {"context":{"requestId":"daac039cd4ad4b8d9849f679d60f3364","requestType":"incoming.Identity_Token","userAgent":"NotSet","clientIp":"177.20.182.4","url":"https://iam.bluemix.net","instanceId":"iamid-4.2-6063-72deb72-5bdbfbc8f9-vk6b8","threadId":"19ac4d","host":"iamid-4.2-6063-72deb72-5bdbfbc8f9-vk6b8","startTime":"16.07.2019 19:23:24:514 UTC","endTime":"16.07.2019 19:23:24:576 UTC","elapsedTime":"62","locale":"en_US","clusterName":"iam-id-prdal10-ljdb"},"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found"}
    at Request._callback (C:\Users\Junior\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:113:21)
    at Request.self.callback (C:\Users\Junior\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:13256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Oq fazer?

**Comment by DanielFelizardoDev** [comment]
Você está colocando uma API inválida, se tiver certo, provavelmente é algum parâmetro escrito de forma errada e tal, se tu poder postar teu código aqui!

**Comment by DanielFelizardoDev** [comment]
Cara, fecha essa issue #210 e deixa em aberto a #209, pois de fato tem o mesmo erro

**Comment by JuniorPetrini** [comment]
o meu esta igual ao do filipe, só baixei seguindo o tutorial do README, só que agora esta tendo outro problemas, esse:
(node:5404) UnhandledPromiseRejectionWarning: Error: {"context":{"requestId":"19f4398d824941598008412d751c96a7","requestType":"incoming.Identity_Token","userAgent":"NotSet","clientIp":"177.20.182.4","url":"https://iam.bluemix.net","instanceId":"iamid-4.2-6063-72deb72-7678fc4976-b4wpj","threadId":"1cb9a9","host":"iamid-4.2-6063-72deb72-7678fc4976-b4wpj","startTime":"19.07.2019 16:59:30:939 UTC","endTime":"19.07.2019 16:59:30:998 UTC","elapsedTime":"59","locale":"en_US","clusterName":"iam-id-prlon04-6r67"},"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found"}
    at Request._callback (C:\Users\Junior\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:113:21)
    at Request.self.callback (C:\Users\Junior\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
@JuniorPetrini confere as credenciais da api do **watson**:
```
"errorMessage":"Provided API key could not be found"
```
chave da Api Informada não pode ser encontrada

**Comment by JuniorPetrini** [comment]
agora deu outro problema:

**Comment by JuniorPetrini** [comment]
(node:4924) UnhandledPromiseRejectionWarning: Error: {"context":{"requestId":"a32befd2a79b4fa5a91332814a67de4b","requestType":"incoming.Identity_Token","userAgent":"NotSet","clientIp":"177.20.182.4","url":"https://iam.bluemix.net","instanceId":"iamid-4.2-6153-109319a-6c6cdd45f7-f7ml8","threadId":"44878","host":"iamid-4.2-6153-109319a-6c6cdd45f7-f7ml8","startTime":"23.07.2019 17:39:54:674 UTC","endTime":"23.07.2019 17:39:54:743 UTC","elapsedTime":"69","locale":"en_US","clusterName":"iam-id-prdal12-8brn"},"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found"}
    at Request._callback (C:\Users\Junior\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:113:21)
    at Request.self.callback (C:\Users\Junior\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (C:\Users\Junior\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:4924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
reinstala o imagimagick e marca essa opção durante as etapas de instalação:
![img](https://manuelmeyer.net/wp-content/uploads/2016/06/image_thumb-3.png)
