### ISSUE TITLE
Problema do robo do youtube (node: 5692)

### ISSUE THREAD

**Issue by ErikCardoso** [filipedeschamps/video-maker#215]
Eu estou com problema após acessar o consentimento (a parte em que entra no link e loga na sua conta), depois de acessar da esse erro.

> [youtube-robot] Consent given: undefined
(node:5692) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undef
ined
    at OAuth2Client.<anonymous> (C:\projeto-video\node_modules\google-auth-library\build\src\
auth\oauth2client.js:122:31)
    at Generator.next (<anonymous>)
    at C:\projeto-video\node_modules\google-auth-library\build\src\auth\oauth2client.js:22:71

    at new Promise (<anonymous>)
    at __awaiter (C:\projeto-video\node_modules\google-auth-library\build\src\auth\oauth2clie
nt.js:18:12)
    at OAuth2Client.getTokenAsync (C:\projeto-video\node_modules\google-auth-library\build\sr
c\auth\oauth2client.js:119:16)
    at OAuth2Client.getToken (C:\projeto-video\node_modules\google-auth-library\build\src\aut
h\oauth2client.js:112:18)
    at Promise (C:\projeto-video\robots\youtube.js:78:21)
    at new Promise (<anonymous>)
    at requestGoogleForAccessTokens (C:\projeto-video\robots\youtube.js:77:14)
(node:5692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error origina
ted either by throwing inside of an async function without a catch block, or by rejecting a p
romise which was not handled with .catch(). (rejection id: 3)
(node:5692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the
 future, promise rejections that are not handled will terminate the Node.js process with a no
n-zero exit code.

O que pode ta ocasionando esse erro?

**Comment by danilosales** [comment]
Confere as suas credencias no google-youtube.json que é utilizado na criação do cliente OAuth, e confere no painel do desenvolvedor do google onde você criou as credenciais, se a url de redirect está correta junto com a porta.

**Comment by MatheusRV** [comment]
Duplicado de https://github.com/filipedeschamps/video-maker/issues/225
