### ISSUE TITLE
Error: Missing required parameters: apikey

### ISSUE THREAD

**Issue by VH-loop** [filipedeschamps/video-maker#235]
Como a instalação do watson-developer-cloud estava dando errado pra mim eu instalei o ibm-watson que é a nova versão. Mas então da esse problema pra mim. Alguém sabe resolver?

C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-cloud-sdk-core\auth\utils\helpers.js:63
        throw missingParamsError;
        ^

Error: Missing required parameters: apikey
    at Object.getMissingParams (C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-cloud-sdk-core\lib\helper.js:102:11)
    at Object.validateInput (C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-cloud-sdk-core\auth\utils\helpers.js:61:39)
    at new IamAuthenticator (C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-cloud-sdk-core\auth\authenticators\iam-authenticator.js:47:17)
    at Object.getAuthenticatorFromEnvironment (C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-cloud-sdk-core\auth\utils\get-authenticator-from-environment.js:63:29)
    at new NaturalLanguageUnderstandingV1 (C:\Users\Kv\Desktop\First\level-mode\node_modules\ibm-watson\natural-language-understanding\v1.js:66:58)
    at Object.<anonymous> (C:\Users\Kv\Desktop\First\level-mode\robots\text.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

**Comment by MatheusRV** [comment]
Conforme o erro diz `Missing required parameters: apikey`, pode porfavor verificar o arquivo de credeciais?

**Comment by leodutra** [comment]
@MatheusRV por favor, marque como bug apenas o que for um bug confirmado. Assim não atrapalha quem estiver fazendo correções.

**Comment by gustavogmartinelli** [comment]
eu instalei a versão anterior mesmo, não tive problema e estou fazendo esse projeto por agora.

Pode parecer besteira mas dá uma olhada nas variáveis que foram declaradas para informar a apiKey, tive esse problema durante as chamadas que foram resolvida assim.

**Comment by leodutra** [comment]
Testei, o projeto não apresenta este problema. Faltou API key.
