### ISSUE TITLE
Erro na hora de executar

### ISSUE THREAD

**Issue by alportblu** [filipedeschamps/video-maker#240]
i5-6500@DESKTOP-KAFK8JC MINGW64 /d/video-maker-master
$ node index.js
internal/modules/cjs/loader.js:1176
    throw err;
    ^

SyntaxError: D:\video-maker-master\credentials\google-search.json: Unexpected st
ring in JSON at position 60
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1173:22)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\video-maker-master\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)

Se alguem conseguir me ajudar agradeco

**Comment by MatheusRV** [comment]
Seu arquivo `google-search.json` provavelmente está com as credenciais invalidas. Você já verificou isso. Muitas pessoas já tiveram esse erro aqui no repositório.
