### ISSUE TITLE
Credenciais do Google Cloud

### ISSUE THREAD

**Issue by natangomess** [filipedeschamps/video-maker#246]
A forma de criação das credenciais mudou, agora precisa ser respondidas mais três perguntas: 

1- De Onde você chamará a API? 
2- Que dados você acessará?
3- Você planeja usar essa API com o App Engine ou o Compute Engine?

O que devo marcar?

**Comment by gustavo-tp** [comment]
Essas perguntas servem apenas para te auxiliar a encontrar o tipo de chave ideal para a sua aplicação, pois existem várias formas de autenticação.

Neste caso o Filipe utilizou a API key, então você já sabe qual chave utilizar e poderá selecioná-la diretamente sem responder essas perguntas.

Se você observar, logo acima das perguntas tem um texto que diz:

> If you wish you can skip this step and create an API key, client ID, ou service account


A palavra "API key" é um link e basta clicar nela, em seguida você dará um nome para sua key, por exemplo "VIDEO_MAKER_API_KEY".

Após isso, caso deseje, poderá adicionar restrições para essa chave como por exemplo quais aplicações poderão utilizar essa chave e qual API poderá ser chamada utilizando essa chave, mas nessa ocasião, por ser apenas um experimento, você pode clicar em "create" sem modificar nada.

Por fim basta copiar sua chave e colar no arquivo JSON do mesmo jeito que o Filipe faz no vídeo.

**Comment by Jeffersontee** [comment]
Galera ainda existe esse campo que ele mostra no video só esta em outro lugar
https://cse.google.com/cse/create/new

**Comment by megavapor** [comment]
fiz assim tudo certinho e ainda recebo erro:
PS E:\videomaker\video-maker> node index.js
internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: E:\videomaker\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\videomaker\video-maker\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
PS E:\videomaker\video-maker>

**Comment by davidruizdiaz** [comment]
> Essas perguntas servem apenas para te auxiliar a encontrar o tipo de chave ideal para a sua aplicação, pois existem várias formas de autenticação.
> 
> Neste caso o Filipe utilizou a API key, então você já sabe qual chave utilizar e poderá selecioná-la diretamente sem responder essas perguntas.
> 
> Se você observar, logo acima das perguntas tem um texto que diz:
> 
> > If you wish you can skip this step and create an API key, client ID, ou service account
> 
> A palavra "API key" é um link e basta clicar nela, em seguida você dará um nome para sua key, por exemplo "VIDEO_MAKER_API_KEY".
> 
> Após isso, caso deseje, poderá adicionar restrições para essa chave como por exemplo quais aplicações poderão utilizar essa chave e qual API poderá ser chamada utilizando essa chave, mas nessa ocasião, por ser apenas um experimento, você pode clicar em "create" sem modificar nada.
> 
> Por fim basta copiar sua chave e colar no arquivo JSON do mesmo jeito que o Filipe faz no vídeo.

Gracias!! Sirvió mucho!
