### ISSUE TITLE
Node index.js

### ISSUE THREAD

**Issue by iamgoncalo** [filipedeschamps/video-maker#268]
Olá a todos, já estou a tentar à horas, e não estou a conseguir resolver este problema.
Será que alguém me pode ajudar?

Muito obrigado!

video-maker goncalo$ node index.js
/Users/goncalo/Downloads/video-maker/index.js:4
	text: require('./robots/text2.js')
	^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by apfjunior** [comment]
Erro de sintaxe. Posta aqui teu código  `index.js`. O erro está na linha 4.

**Comment by iamgoncalo** [comment]
ah sim! Obrigado!

**Comment by leohmoraes** [comment]
Resolvido?

> ah sim! Obrigado!

**Comment by iamgoncalo** [comment]
sim, este sim ahahah Parece que há mais problemas que nunca mais acabam. Muito obrigado pela vossa grande ajuda,

Gonçalo

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
