### ISSUE TITLE
i dont know how to fix this error doesnt continuo search 

### ISSUE THREAD

**Issue by jpldias** [filipedeschamps/video-maker#280]
PS C:\Users\Zaziel\Desktop\video-maker-master\video-maker> node index.js
Type a Wikipedia search term: Taylor Swift

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Taylor Alison Swift is an American singer-songwriter."
(node:6852) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Zaziel\Desktop\video-maker-master\video-maker>

**Comment by jpldias** [comment]
i allready made a new ibm api and its the same problem
