### ISSUE TITLE
Não passa das opções []what is.... e trava quando se digita apenas uma palavra tipo batata

### ISSUE THREAD

**Issue by Gizati** [filipedeschamps/video-maker#284]
C:\Users\alfre_000\Desktop\ROBO\video-maker>node index.js
Type a Wikipedia search term: ThetaHealing

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "ThetaHealing is the registered trademark for a process of meditation created by Vianna Stibal in 1995."
(node:4268) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\alfre_000\Desktop\ROBO\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\alfre_000\Desktop\ROBO\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\alfre_000\Desktop\ROBO\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\alfre_000\Desktop\ROBO\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1225:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bcgs** [comment]
Resolveu?

O Watson não tá recebendo a credencial correta. Pode ser alguma alteração na chave ou simplesmente um erro sintático ao chamar `apikey` do JSON. Dá uma olhada se você tá chamando a `apikey` corretamente ou se a chave disponibilizada lá na conta do Watson tá batendo com a do seu JSON.

Se conseguir solucionar fecha a issue. ✌🏼

**Comment by Gizati** [comment]
Nope, desisto.
