### ISSUE TITLE
Erro no run do programa

### ISSUE THREAD

**Issue by jpldias** [filipedeschamps/video-maker#288]
Ola estou a ter um erro e não percebo o porque.....

Isto e o que me esta aparecer se me poderem ajudar agradeço

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Cristiano Ronaldo dos Santos Aveiro GOIH ComM is a Portuguese professional footballer who plays as a forward for Serie A club Juventus and captains the Portugal national team."
(node:29824) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (C:\Users\Zaziel\Desktop\video-maker-master\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:29824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandl
ed promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Zaziel@DESKTOP-J52UAJA MINGW64 ~/Desktop/video-maker-master/video-maker (master)
$

**Comment by Jeffersontee** [comment]
Tem que olhar as credenciais esta com erro

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
