### ISSUE TITLE
Erro node:38986

### ISSUE THREAD

**Issue by gabrieltodino** [filipedeschamps/video-maker#293]
Estou com problemas no robô de textos, se alguém conseguir me ajudar. Desde já agradeço

`(node:38986) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received undefined
    at write_ (_http_outgoing.js:661:11)
    at ClientRequest.write (_http_outgoing.js:629:15)
    at AlgorithmiaClient.req (/home/gabrieltodino/Programation/Video-maker/node_modules/algorithmia/lib/algorithmia.js:117:19)
    at Algorithm.pipe (/home/gabrieltodino/Programation/Video-maker/node_modules/algorithmia/lib/algorithm.js:27:28)
    at fetchContentFromWikipedia (/home/gabrieltodino/Programation/Video-maker/robots/text.js:10:58)
    at Object.robot [as text] (/home/gabrieltodino/Programation/Video-maker/robots/text.js:5:5)
    at start (/home/gabrieltodino/Programation/Video-maker/index.js:12:13)
    at Object.<anonymous> (/home/gabrieltodino/Programation/Video-maker/index.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
(node:38986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by bcgs** [comment]
Talvez você esteja passando o JSON pro _Algorithmia_ ao invés da **chave** `apikey`.

Sugiro dar uma olhada no seu import e verificar se tá assim:

`const algorithmiaApiKey = require('../credentials/algorithmia.json').apikey;`

**Comment by gabrieltodino** [comment]
Não deu certo cara, já estava desse jeito que você disse, mesmo assim agradeço. Irei colocar o código logo abaixo.

```
const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey;

function robot(content) {  
    fetchContentFromWikipedia(content)
  
    async function fetchContentFromWikipedia(content) {
      const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
      const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
      const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
      const wikipediaContent = wikipediaResponse.get()
  
      console.log (wikipediaContent)
  }
}

module.exports = robot
```
