### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:5196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by ifra1000** [filipedeschamps/video-maker#298]
hoose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "William Henry Gates III is an American business magnate, software developer, investor, and philanthropist."
(node:5196) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (D:\github\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (D:\github\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (D:\github\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (D:\github\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by M3G4THEKING** [comment]
@ifra1000  Hi, well this seems the problems is in background of IBM Cloud company, check the status above.
We need to way or find another way to do.
https://cloud.ibm.com/status?selected=status

**Comment by matbrgz** [comment]
Is this solved? I hope you got it.
I am closing error-related issues to understand which errors still exist, which have already been resolved, and if necessary I can open them again.
