### ISSUE TITLE
node.js no postman

### ISSUE THREAD

**Issue by julio-byte** [filipedeschamps/video-maker#299]
tenho um erro na hora de usar no postman, quando uso git bash pra rodar o node index.js

ReferenceError: getUsers is not defined
at C:\Users\fabio\node.js\Routers\UserRouters.js:30:27
at Layer.handle [as handle_request] (C:\Users\fabio\node.js\node_modules\express\lib\router\layer.js:95:5)
at next (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:137:13)
at next (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:131:14)
at Route.dispatch (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:112:3)
at Layer.handle [as handle_request] (C:\Users\fabio\node.js\node_modules\express\lib\router\layer.js:95:5)
at C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:281:22
at param (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:354:14)
at param (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:365:14)
at Function.process_params (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:410:3)

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
