### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by matheuspellisoli** [filipedeschamps/video-maker#31]
Alguém sabe como realizar a correção desse erro? 

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/app/video-maker/robots/text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

**Comment by maykbrito** [comment]
> Error: Cannot find module '../credentials/algorithmia.json'

Ele não achou esse arquivo nesse caminho

**Comment by Jrfidellis** [comment]
@matheuspellisoli dá uma olhada aqui: #28

**Comment by Pacheco95** [comment]
@matheuspellisoli Quando você criar uma issue, dê um título mais explicativo! Abraços!

**Comment by VinyciusC** [comment]
Você tem que criar em "..\credentials\" uma arquivo com o nome "algorithmia.json" ai você coloca esse código aqui:
`{
  "apiKey": "SUAAPIKEY"
}`

A API você deve se registrar no site [algorithmia.com](https://algorithmia.com) e criar uma conta, depois
![image](https://user-images.githubusercontent.com/48515934/54291177-f5041680-458a-11e9-8867-6e6a7b6e88d4.png)
