### ISSUE TITLE
Split Undefined

### ISSUE THREAD

**Issue by PedroWagnerBomfim** [filipedeschamps/video-maker#310]
(node:10320) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at removeBlankLinesAndMarkdown (/home/pedro/projetos/Sistema-Video-Maker/robots/text.js:31:35)
    at sanitizeContent (/home/pedro/projetos/Sistema-Video-Maker/robots/text.js:22:46)
    at Object.robot [as text] (/home/pedro/projetos/Sistema-Video-Maker/robots/text.js:6:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (/home/pedro/projetos/Sistema-Video-Maker/index.js:13:3)
(node:10320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Como resolver?

**Comment by faustoct** [comment]
A api do wikipedia as vezes não encontrar o que vc procura, devido ambiguidade no próprio Wikipédia. Por exemplo para gerar vídeo do Elon Musk, vc deve usar o termo de pesquisa 'Elon Reeve Musk'. 

Qual o termo da pesquisa?
