### ISSUE TITLE
Erro ao executar o comando node index.js

### ISSUE THREAD

**Issue by PedroWagnerBomfim** [filipedeschamps/video-maker#319]
Ao executar o comando  'node index.js' no terminal, o sistema dá o erro:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'readline-sync'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/input.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by LeonardoDalessandro** [comment]
Parece que falta o modulo "readline-sync".
Olha se vc encontra como dependencia essa linha no arquivo package.json:
```
"readline-sync": "^1.4.9",
```

**Comment by PedroWagnerBomfim** [comment]
@LeonardoDalessandro  eu adicionei o modulo no arquivo package.json, porem o sistema retornou o erro abaixo.

` node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'readline-sync'
Require stack:
- /home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/input.js
- /home/pedro/Documentos/projetos/Sistema-Video-Maker/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/input.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/input.js',
    '/home/pedro/Documentos/projetos/Sistema-Video-Maker/index.js'
  ]
}
`

Segue a imagem package.json

![image](https://user-images.githubusercontent.com/17617563/101107862-050b2780-35b2-11eb-9ce9-21ff92cf7934.png)

**Comment by MatheusRV** [comment]
Parece que vc não rodou o comando yarn ou npm i para sincronizar as dependências. Estou fechando aqui qualquer dúvida pode comentar que reabrimos.

**Comment by PedroWagnerBomfim** [comment]
Poderia me esclarecer como sincronizar atis dependências?

**Comment by MatheusRV** [comment]
> Poderia me esclarecer como sincronizar atis dependências?

Abra o terminal na pasta do projeto e execute o comando yarn ou npm i

**Comment by LeonardoDalessandro** [comment]
So pra tirar a duvida/possibilidade de conflitos entre versoes:
tenta fazer um update do node e do npm tambem.
Depois tenta baixar de novo todas as dependencias pra ver o resultado.

**Comment by PedroWagnerBomfim** [comment]
@LeonardoDalessandro 

Cara, deu certo.... Muito obrigado pela dica!

**Comment by LeonardoDalessandro** [comment]
De nada!
