### ISSUE TITLE
Erro no readlyne-sync

### ISSUE THREAD

**Issue by carlosgiovani** [filipedeschamps/video-maker#320]
Esse arquivo esta faltando, ele e criado automaticamente ou como devo criar???

Erro
$ node index.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'readline-sync'
Require stack:
- /Users/nome/Documents/RoboVideos/video-maker-master/robots/input.js
- /Users/nome/Documents/RoboVideos/video-maker-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nome/Documents/RoboVideos/video-maker-master/robots/input.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nome/Documents/RoboVideos/video-maker-master/robots/input.js',
    '/Users/nome/Documents/RoboVideos/video-maker-master/index.js'
  ]
}

**Comment by LeonardoDalessandro** [comment]
Olha, esse problema foi resolvido aqui:
https://github.com/filipedeschamps/video-maker/issues/319#issuecomment-739109461

Caso persistir o erro, vamos ver como resolver de outra forma.

**Comment by carlosgiovani** [comment]
Agora esta fazendo a pesquisa, mas acho q nao esta trazendo as imagens e nem publicando o video. Como posso verificar esse problema?

**Comment by LeonardoDalessandro** [comment]
Se esse problema foi resolvido, por favor fecha essa issue e abri uma outra com o detalhe de um dos problema especifico. Isso è sò para deixar tudo mais ordenado e simples. A gente vai ter o maior prazer em te ajudar. Beleza? Obrigado.

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
