### ISSUE TITLE
internal/modules/cjs/loader.js:883

### ISSUE THREAD

**Issue by PedroWagnerBomfim** [filipedeschamps/video-maker#321]
Prezados, 

Ao executar o comando 'node index.js' no terminal o sistema reportou o seguinte erro.

`internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/pedro/Documentos/projetos/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
`

Em seguida executei o camando 'sudo npm install express' no diretório do projeto, visando instalar todas as dependências necessárias para você rodar o projeto. 

Logo após sincronizei as dependências do projeto com os comando yarn ou npm i.

Ao rodar novamente o comando  'node index.js', o sistema reporta o mesmo erro.

**Comment by PedroWagnerBomfim** [comment]
Prezados,


Para realizar a correção do erro foi necessário realizar a atualização dos módulos, executando os seguintes comandos dentro do diretório do projeto.

`$ sudo Yarn`

`$ sudo npm i`

`$ sudo npm install googleapis `
