### ISSUE TITLE
Erro na hora de executar o index.js

### ISSUE THREAD

**Issue by RogerBrusamarello** [filipedeschamps/video-maker#57]
copia do erro que acontece no terminal
roger@roger-Inspiron-5566:~/video-maker$ node index.js
Type a Wikipedia search term: michael jackson

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
{ serchTerm: 'michael jackson', prefix: 'Who is' }
(node:14020) UnhandledPromiseRejectionWarning: ReferenceError: wikipediaAlgorithmia is not defined
    at fetchContentFromWikipedia (/home/roger/video-maker/robots/text.js:12:29)
    at Object.robot [as text] (/home/roger/video-maker/robots/text.js:5:2)
    at start (/home/roger/video-maker/index.js:12:9)
    at Object.<anonymous> (/home/roger/video-maker/index.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
(node:14020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vsalbuq** [comment]
`ReferenceError: wikipediaAlgorithmia is not defined`

Não sei se você clonou o repositório, @RogerBrusamarello, mas se digitou na mão, provavelmente essa variável está com o nome errado.

Aqui no repo é `wikipediaAlgorithm` (lá no `robots/text.js`).

**Comment by RogerBrusamarello** [comment]
depois de mudar a variavel para wikipediaAlgorithm no robots/text.js acontece isso
Choose one option [1, 2, 3, 0]: 1
{ serchTerm: 'Michael Jackson', prefix: 'Who is' }
(node:16787) UnhandledPromiseRejectionWarning: TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:642:11)
    at ClientRequest.write (_http_outgoing.js:617:10)
    at AlgorithmiaClient.req (/home/roger/video-maker/node_modules/algorithmia/lib/algorithmia.js:117:19)
    at Algorithm.pipe (/home/roger/video-maker/node_modules/algorithmia/lib/algorithm.js:27:28)
    at fetchContentFromWikipedia (/home/roger/video-maker/robots/text.js:12:54)
    at Object.robot [as text] (/home/roger/video-maker/robots/text.js:5:2)
    at start (/home/roger/video-maker/index.js:12:9)
    at Object.<anonymous> (/home/roger/video-maker/index.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:16787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vsalbuq** [comment]
Posta o código do seu `text.js` e do seu `index.js`, na raiz.

**Comment by MatheusDeAquino** [comment]
Fiz tudo certo até chegar na parte em que o @filipedeschamps abre o index,js e tudo funfa certinho de letra verde.
O meu aparece esse erro aqui sobre não achar meu 'algorithmia':

Error: Cannot find module 'algorithmia'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Matheus\Programação 2018.19\auto-video-project\aut
o-videos\robots\text.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by vsalbuq** [comment]
> Fiz tudo certo até chegar na parte em que o @filipedeschamps abre o index,js e tudo funfa certinho de letra verde.
> O meu aparece esse erro aqui sobre não achar meu 'algorithmia':
> 
> Error: Cannot find module 'algorithmia'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
> at Function.Module._load (internal/modules/cjs/loader.js:508:25)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (D:\Matheus\Programação 2018.19\auto-video-project\aut
> o-videos\robots\text.js:1:83)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)

Pode postar o código do seu `robots/text.js`?

**Comment by danielschmitz** [comment]
> Error: Cannot find module 'algorithmia'

Você fez `npm install --save algorithmia` ?

**Comment by Sauloleocadio** [comment]
(node:8420) UnhandledPromiseRejectionWarning: authorization required
(node:8420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leodutra** [comment]
@Sauloleocadio o seu error é de autorização em alguma API. Verifique a credencial.
Você pode usar o debug do seu editor ou o configurar e usar o stacktrace do módulo make-promises-safe, para encontrar onde ocorre a falha.

**Comment by rodrigofaustino** [comment]
**quem pode ajudar com este erro?**

### **\video-maker>**node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user0330\Downloads\video-maker\robots\text.j
s:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by danielschmitz** [comment]
@rodrigofaustino o #87 vai resolver esse seu problema

**Comment by nutbr** [comment]
Boa noite pessoal. Primeiramente meus parabens pela iniciativa. Como hobbie baixei para testar apos assistir seu video no youtube. Apos alguns tropecos nao consegui sair da seguinte tela. Alguem poderia por gentileza ver se consegue dar uma luz?
Choose one option [1, 2, 3, 0]: 3
> [0][0] Baixou imagem com sucesso: https://ak9.picdn.net/shutterstock/videos/73
27429/thumb/1.jpg
> [1][0] Baixou imagem com sucesso: http://www.coolgeography.co.uk/A-level/AQA/Y
ear%2013/World%20Cities/Sustainability/Curitiba_population.jpg
> [2][0] Baixou imagem com sucesso: https://image.slidesharecdn.com/gladimir-160
120172722/95/experiences-and-challenges-in-the-transport-integrated-net-of-curit
iba-and-the-metropolitan-area-transforming-transportation-2016-3-638.jpg?cb=1453
311056
> [3][0] Baixou imagem com sucesso: https://i.guim.co.uk/img/media/d744090bcadb3
7d3af1846db993a493d75d929bf/0_264_5546_3327/master/5546.jpg?width=700&quality=85
&auto=format&fit=max&s=306ecf05867261e46f2840e02cea38e2
> [4][0] Baixou imagem com sucesso: https://upload.wikimedia.org/wikipedia/commo
ns/6/6b/Collage_Curitiba.png
> [5][0] Baixou imagem com sucesso: https://upload.wikimedia.org/wikipedia/commo
ns/thumb/e/ea/CuritibaTradeCenterSkyline.jpg/250px-CuritibaTradeCenterSkyline.jp
g
> [6][0] Erro ao baixar (https://upload.wikimedia.org/wikipedia/commons/6/6b/Col
lage_Curitiba.png): Error: Imagem já foi baixada
> [6][1] Baixou imagem com sucesso: https://static.smarttravelapp.com/data/pois/
19899_C1_1522913248.jpg
(node:7240) UnhandledPromiseRejectionWarning: Error: Command failed: Invalid Par
ameter - /content

    at ChildProcess.onExit (C:\video-maker\node_modules\gm\lib\command.js:301:17
)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (C:\video-maker\node_modules\cross-spawn\lib\enoent.
js:40:29)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:7240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:7240) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
