### ISSUE TITLE
como rodar o projeto?

### ISSUE THREAD

**Issue by eliaskill** [filipedeschamps/video-maker#86]
desculpe a burrice mais não manjo nada de js! como faço para rodar ? sei bem pouco de python e lá eu uso anaconda ou algo assim mais nesse projeto estou perdido :(

**Comment by mathgama** [comment]
Tenta executar o comando "node index" no terminal.

**Comment by eliaskill** [comment]
PS C:\Users\PCzin\Desktop\py\video-maker-master> node index
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\PCzin\Desktop\py\video-maker-master\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by felipevlima** [comment]
Você tem que criar sua própria pasta credentials com as credenciais da sua conta do Algorithmia e do Watson

**Comment by danielschmitz** [comment]
Veja #87
