### ISSUE TITLE
Estrutura de dados

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/video-maker#9]
```js
content: {
  searchTerm: "...",
  prefix: "...",
  sourceContentOriginal: "...",
  sourceContentSanitized: "...",
  sentences: [
  {
    text: "...",
    keywords: ["..."],
    images: ["..."]
  }
]
}
```

**Comment by lucianopf** [comment]
Identando certinho 😬 😂 
```
content: {
  searchTerm: "...",
  prefix: "...",
  sourceContentOriginal: "...",
  sourceContentSanitized: "...",
  sentences: [
    {
      text: "...",
      keywords: ["..."],
      images: ["..."]
    }
  ]
}
```

**Comment by Sxigames** [comment]
Teste

Em qui, 28 de fev de 2019 00:20, Filipe Deschamps <notifications@github.com>
escreveu:

**Comment by filipedeschamps** [comment]
hahhahahaa @lucianopf matou a pau! Quando gravei o vídeo até falei que a identação ficou errada, obrigado, atualizei a issue com sua versão 👍

**Comment by Kaypira** [comment]
Pessoal criei um servidor do discord para nós inscritos do Filipe, caso tenham interesse em entrar, segue o link abaixo:

https://discord.gg/Q73zZ6J (Filipe, desculpa usar o seu nome, mas como comentei e você apoiou, decidi adiantar a ideia para facilitar a comunicação entre nós em projetos, ideias novas para o canal e etc)

**Comment by matheuschimelli** [comment]
@Kaypira spam NÃO né

**Comment by israelsousa21** [comment]
Cara isso tá ficando muito bom :D

**Comment by Jrfidellis** [comment]
@filipedeschamps, as estruturas de dados estão começando a ficar complexas, não cairia bem um TypeScript? Estou disposto a ajudar com isso :)

**Comment by lucianopf** [comment]
@Jrfidellis eu concordo que ajudaria sim mas talvez a complexidade que introduziria a novos programadores fosse um pouco mais alta, e daí como o projeto é ajudar/ensinar devs de todos os tipos acho que fugiria um pouco do propósito 🤔 
O que acham @filipedeschamps @Jrfidellis ?

**Comment by Jrfidellis** [comment]
Certamente iria aumentar a complexidade no primeiro momento, mas também traria vantagens para eles (tipagem), o que facilitaria o desenvolvimento evitando erros bobos. Agora estou na dúvida se valeria a pena..

**Comment by lucianopf** [comment]
Exatamente hehehe, essa é uma briga eterna que eu tenho com o TypeScript, para muitos casos eu vejo a vantagem superior a desvantagem, mas para projetos em que o objetivo é lecionar E/OU mentorar acredito que as desvantagens são maiores 🤔 

Bem, bora aguardar o parecer do mestre dos mestres @filipedeschamps ! 🤓  hehehe

**Comment by HiltonWS** [comment]
> Exatamente hehehe, essa é uma briga eterna que eu tenho com o TypeScript, para muitos casos eu vejo a vantagem superior a desvantagem, mas para projetos em que o objetivo é lecionar E/OU mentorar acredito que as desvantagens são maiores 
> 
> Bem, bora aguardar o parecer do mestre dos mestres @filipedeschamps !  hehehe

Vejo que o Typescript está sendo migrado em diversas ferramente o qual iniciou com Angular e foi para o React e afins, então não vejo mal coloca-lo, porém como é um script mais orientado, talvez teria uma curva de aprendizado maior para entender os conceitos, porém no mercado, o que mais verá será ferramentas com TS.

**Comment by Jrfidellis** [comment]
Galera, criei uma versão do `robot.js` com TypeScript, aqui está a comparação: https://www.diffchecker.com/oBWTovFi

Será que a complexidade aumentou taaanto assim? Queria ouvir as opiniões.
Além de alterar esse arquivo, precisei criar um novo para colocar os tipos:
![image](https://user-images.githubusercontent.com/26925730/54061462-badbf300-41df-11e9-8f7a-b6ebf80e4970.png)

**Comment by maycrodrigues** [comment]
@Jrfidellis eu também estou criando a versão em TS. 🚀

**Comment by Patricia7sp** [comment]
Boa tarde!

Pessoal, como estão?

Estou tendo um problema quando  digito o comando node index.js -  não esta funcionando e esta aparecendo este erro

module.js:549
    throw err;
    ^

Error: Cannot find module 'sbd'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/patricia/rob-s-maker/robots/text.js:3:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Alguém consegue me dar um help?

Tentei buscar uma solução e não consegui.

**Comment by Jrfidellis** [comment]
Oi @Patricia7sp, tudo bem :)

Recomendo que você abra outra issue perguntando sobre isso (se ninguém já o fez), só pra não misturar os assuntos mesmo. Ficarei feliz em te ajudar por lá.

**Comment by Patricia7sp** [comment]
@Jrfidellis Ola, na vdd vc. esta certo, eu criei uma  issue. Se conseguir me ajudar ficarei muito feliz.
