### ISSUE TITLE
Poderiam me ajudar com este erro?

### ISSUE THREAD

**Issue by Guitarfreaks** [filipedeschamps/video-maker#95]
Fala galera, boa tarde!

Sou iniciante no mundo da programação e estou tentando acompanhar as aulas do Filipe, até agora está indo tudo bem mas do nada me deparei com este erro e não estou conseguindo identificar onde errei. Conferir todo código e realmente não sei o que houve. Alguém poderia me ajudar?

Estou no vídeo: Deep Learning, Web Scraping e Processamento de Linguagem Natural (API grátis) aos 11:25

Se precisarem posso colar meu código também.

Obrigado!

AndreSugaisMBP:video-maker-sugai-video2 guitarfreaks$ node index.js
/Users/guitarfreaks/Desktop/video-maker/video-maker-sugai-video2/index.js:4
    text: require('./robots/text.js')
    ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
AndreSugaisMBP:video-maker-sugai-video2 guitarfreaks$

**Comment by vsalbuq** [comment]
@Guitarfreaks É erro de sintaxe (você escreveu algo errado).

Coloca o código do seu `index.js` aí pra gente conseguir ver o que é.

**Comment by Guitarfreaks** [comment]
Oi @vsalbuq , olhar o meu index.js:

const readline = require('readline-sync')
const robots = {
    userInput: require('./robots/user-input.js')
    text: require('./robots/text.js')
}
function start (){
    const content = {}
    
    robots.userInput(content)
    robots.text(content)

    console.log(content)
    
}

start()

**Comment by vsalbuq** [comment]
@Guitarfreaks faltou uma vírgula no fim da linha. Faz assim que vai dar certo:

```js
const robots = {
    userInput: require('./robots/user-input.js'),
    text: require('./robots/text.js')
}
```

**Comment by Guitarfreaks** [comment]
Oi @vsalbuq ,

Ainda persiste o erro, olha o código da minha index.js com a alteração:

const readline = require('readline-sync')
const robots = {
    userInput: require('./robots/user-input.js'),
    text: require('./robots/text.js')
}
function start (){
    const content = {}
    
    robots.userInput(content)
    robots.text(content)

    console.log(content)
    
}

start()

E olha o código do erro que deu depois que rodei a index.js com a alteração:

AndreSugaisMBP:video-maker-sugai-video2 guitarfreaks$ node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './robots/user-input.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/guitarfreaks/Desktop/video-maker/video-maker-sugai-video2/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
AndreSugaisMBP:video-maker-sugai-video2 guitarfreaks$

**Comment by Guitarfreaks** [comment]
Só para deixar claro estou fazendo o projeto do zero e o input-user.js ainda não existe na pasta de robots. Estou seguindo o vídeo, que no caso, rodou normalmente sem o input-user.js ter sido criado.

**Comment by vsalbuq** [comment]
> Só para deixar claro estou fazendo o projeto do zero e o user-input.js ainda não existe na pasta de robots. Estou seguindo o vídeo, que no caso, rodou normalmente sem o user-input.js ter sido criado.

O primeiro erro era por falta da vírgula. O segundo é diferente. Perceba que no erro ele diz `Cannot find module './robots/user-input.js'`. É exatamente esse o erro.

Se for seguir o vídeo, faça como está lá. O código aqui está um pouco mais avançado.

**Comment by Guitarfreaks** [comment]
Obrigado @vsalbuq !! Consegui resolver, voltei a usar o index.js com o código anterior :)
